### ISSUE TITLE
Font BBox differs between head table and CFF for Italics

### ISSUE THREAD

**Issue by erniemarch** [adobe-fonts/source-sans-pro#146] opened 2018-09-18 14:30 UTC
Single Face Test 15: Warn if Font BBox x/y coordinates are improbable, or differ between head table and CFF.
The font bounding box in the hhea table '(-323, -291, 2077, 969)' differs from that in the CFF table '[-506, -291, 2077, 969]'. SourceSansPro-It.
The font bounding box in the hhea table '(-321, -313, 2078, 1007)' differs from that in the CFF table '[-506, -313, 2078, 1007]'. SourceSansPro-BoldIt.
The font bounding box in the hhea table '(-320, -322, 2078, 1023)' differs from that in the CFF table '[-506, -322, 2078, 1023]'. SourceSansPro-BlackIt.
The font bounding box in the hhea table '(-324, -288, 2076, 938)' differs from that in the CFF table '[-506, -288, 2076, 938]'. SourceSansPro-ExtraLightIt.
The font bounding box in the hhea table '(-324, -281, 2076, 946)' differs from that in the CFF table '[-506, -281, 2076, 946]'. SourceSansPro-LightIt.
The font bounding box in the hhea table '(-322, -303, 2077, 988)' differs from that in the CFF table '[-506, -303, 2077, 988]'. SourceSansPro-SemiboldIt.

**Comment by miguelsousa** [comment] 2018-09-20 00:13
This is caused by a [bug in **makeotfexe**](https://github.com/adobe-type-tools/afdko/issues/617). The fix is non-trivial and there's higher priority issues to get to. So, in the meantime, I'm planning to add a workaround in **makeotf**.

**Comment by miguelsousa** [comment] 2018-10-27 07:02
makeotfexe got fixed in afdko v2.8.3b0. New font builds were made with this version.

**Closed by miguelsousa** 2018-10-27 07:02 UTC
