### ISSUE TITLE
How are the instances built from the masters?

### ISSUE THREAD

**Issue by khaledhosny** [adobe-fonts/source-sans-pro#77] opened 2015-09-30 11:08 UTC
I’m exploring using Source Sans Pro as a Latin companion to an Arabic typeface I’m working on, so I’m trying to understand the workflow.

While the masters are included in the repository, the interpolated instances are committed individually and there aren’t any build scripts to generate them in the repository AFAICT.

I tried using `UFOInstanceGenerator.py` but the `instances` file it needs is not included, which suggests that it is not what you use to generate the instances (though creating such a file from `*.designspace` wasn’t hard and `UFOInstanceGenerator.py` happily generated the instances after that).

**Comment by moyogo** [comment] 2015-09-30 11:12
I’d also be interested to have a more complete build process from the masters.

@khaledhosny makeInstancesUFO is used, for example `makeInstancesUFO -d RomanMasters/SourceSansPro.designspace`.

**Comment by miguelsousa** [comment] 2015-09-30 11:14
Use the FDK's `makeInstancesUFO`. This tool will make the instances (`font.ufo` fonts) and also process them thru `checkOutlinesUFO` and `autohint`.

**Comment by moyogo** [comment] 2015-09-30 11:16
Why keep the instances in the repository if they are generated in a reproducible way?

**Comment by miguelsousa** [comment] 2015-09-30 11:31
Creating, removing overlaps, and hinting the instances can take a significant amount of time.
Being able to run only `makeOTF` when there are only fixes to be made to the table metadata and no changes to the outlines are required, is a big bonus (and also guarantees that the instance outlines have indeed not changed from one version to another).

**Comment by khaledhosny** [comment] 2015-09-30 11:53
OK, that is good enough for me. What version of AFDKO is used because I’m getting an error in the post-processing step which looks like a bug in `checkOutlinesUFO`:
````
Applying post-processing
        doing overlap removal with checkOutlinesUFO ../Italic/ExtraLightIt/font.ufo ...
Traceback (most recent call last):
  File "/afdko/FDK/Tools/linux/../SharedData/FDKScripts/CheckOutlinesUFO.py", line 967, in <module>
    run(sys.argv[1:])
  File "/afdko/FDK/Tools/linux/../SharedData/FDKScripts/CheckOutlinesUFO.py", line 908, in run
    newGlyph, glyphDigest, changed, msg = test(newGlyph, glyphDigest, changed, msg, options)
  File "/afdko/FDK/Tools/linux/../SharedData/FDKScripts/CheckOutlinesUFO.py", line 711, in doOverlapRemoval
    changed, msg = removeTinySubPaths(newGlyph, options.minArea, changed, msg) # Tiny subpaths are added by overlap removal.
  File "/afdko/FDK/Tools/linux/../SharedData/FDKScripts/CheckOutlinesUFO.py", line 485, in removeTinySubPaths
    cArea = (cBounds[2] - cBounds[0])*(cBounds[3] - cBounds[1])
TypeError: 'NoneType' object has no attribute '__getitem__'


Error in checkOutlinesUFO ../Italic/ExtraLightIt/font.ufo
Quitting after error.
````

**Comment by miguelsousa** [comment] 2015-09-30 12:09
I don't know, and we don't have a way check it. The only reference in the fonts referes to makeotf.lib only. See `name` table.
Read has been making several fixes to the cutting-edge version we use internally, and a public release is eminent. I agree that it seems to be a bug in checkoutlinesUFO, but I wonder if it only happens on Linux.

**Comment by khaledhosny** [comment] 2015-09-30 12:16
The Roman instances were generated successfully, only the Italic ones show this bug. I’ll see if I can reproduce this on Mac (but it might take a while as my Mac machine is not set up for development). But I see lots of differences, mostly in `com.typemytype.robofont.layerData` lib. I guess I’ll have to try with the official AFDKO not my self-built one.

**Comment by grzegorzrolek** [comment] 2015-09-30 15:30
> Creating, removing overlaps, and hinting the instances can take a significant amount of time.
Being able to run only `makeOTF` when there are only fixes to be made to the table metadata and no changes to the outlines are required, is a big bonus (and also guarantees that the instance outlines have indeed not changed from one version to another).

BTW, wouldn’t a simple makefile take care of all this? Once built, the instances won’t even be touched unless the masters change, or unless deliberately messed with.

**Comment by miguelsousa** [comment] 2015-10-01 00:12
I'd like to clarify that the source files in this repository are always fully up to date with what we use internally. What lags a bit behind are the downloadable FDK builds.

**Comment by miguelsousa** [comment] 2015-10-01 00:14
> BTW, wouldn’t a simple makefile take care of all this? Once built, the instances won’t even be touched unless the masters change, or unless deliberately messed with.

I don't know. If you care to submit a PR we'll be able to evaluate what you have in mind.

**Comment by grzegorzrolek** [comment] 2015-10-01 14:23
> If you care to submit a PR we'll be able to evaluate what you have in mind.

OK, I’ll prepare it over the weekend.

I’m sure for some of you this is obvious, but using `make` instead of a build-all shell script really makes a difference, both in build times and in terms of automation. Anyway, I’ll prepare it so that both methods could co-exist and the whole team could get familiar with it, see how it performs, and then decide to do the switch or not. Also, even with an entirely automated build, the instances could still be stored in the repo and committed each time the outlines change if that helps with QA.

FWIW, I wrote a similar makefile for Adobe-style setup a few years ago in [a project of mine](https://github.com/grzegorzrolek/kontrapunkt-pro), and it all worked very well (though it hasn’t been updated with the more recent FDK builds). It was rather convoluted, as there was a lot happening at build time, but in this case it should be pretty straightforward.

**Comment by grzegorzrolek** [comment] 2015-10-04 19:13
Regarding the error Khaled reported earlier: same thing on OS X with a fresh build from the current master of the FDK, including the differences found in the generated instances.

**Comment by khaledhosny** [comment] 2015-11-03 19:07
This moved forward a bit after fixing https://github.com/typemytype/booleanOperations/pull/10. Now if I added a new instance to `SourceSansPro.designspace`, say Medium with weight 520, I get a `font.ufo` file under `Roman/Medium/` but nothing else, no features files, no `derivedchars_TT` (not that I know what it is for),  no `fontinfo` and so on. Not sure what I’m missing, do I need to create these files manually?

**Comment by pauldhunt** [comment] 2015-11-03 19:15
@khaledhosny i have written the `features` files and the `fontinfo` files by hand (more accurately, i copied these then edited the entries). are you creating TrueType fonts? if not, you will not need the `derived_TT` file – this is used for recomposing composite glyphs in the TT font.

**Comment by khaledhosny** [comment] 2015-11-03 19:22
OK, good to know. I was confused because the masters have `derivedchars_{0,1}` and `anchors_{0,1}` so I assumed they are used to generate something.

**Comment by khaledhosny** [comment] 2015-11-03 19:33
Were the mark features really modified by hand? That seems too much work given that the anchors are already in the UFO font.

**Comment by pauldhunt** [comment] 2015-11-03 19:33
@khaledhosny the files `derivedchars_x` and `anchors_x` are not used directly to generate any features, but to store positioning information in an external file that can be output and input via scripts. Scripts are also used to generate mark features from interpolated information in the various style instances.

**Comment by khaledhosny** [comment] 2015-11-03 19:38
I see. Are these scripts publicly available or do I need to roll my own? (Sorry for too much asking, but this is all really over my head).

**Comment by pauldhunt** [comment] 2015-11-03 19:47
i believe that the scripts that output kerning and mark features are here:
https://github.com/adobe-type-tools/python-scripts

**Comment by frankrolf** [comment] 2015-11-03 19:49
However, the mechanism for creating `derivedchars` files is not public.
It is quite old (and maybe worth re-thinking), it is just the way we’ve been creating our accents (and other components) all along.

**Comment by khaledhosny** [comment] 2015-11-03 20:30
OK, for the record here is what I did to create a new Medium instance:
* Edited `RomanMasters/SourceSansPro.designspace` to add a new instance, with with weight value of 520.
* Ran `makeInstancesUFO -i 3 -d RomanMasters/SourceSansPro.designspace` to generate the new file.
* Ran `UFOInstanceGenerator.py RomanMasters/ -o Roman/Medium -kern -mark -mkmk -clas -nufo` to generate font features without overriding the previously generated UFO file.
    * This requires creating a `RomanMasters/instances` file.
* Copied `Roman/Regular/features` to `Roman/Medium/features`
* Edited `FontMenuNameDB` to added names for the new instance.
* Finally ran `makeotf -f Roman/Medium/font.ufo -r -o target/OTF/SourceSansPro-Medium.otf` to generate the OTF file.
    * This is currently failing because of kerning overflow, investigating.

**Comment by miguelsousa** [comment] 2015-11-03 23:06
@khaledhosny our plan is to at some point hook up [WriteFeaturesKernFDK](https://github.com/adobe-type-tools/python-modules) and [WriteFeaturesMarkFDK](https://github.com/adobe-type-tools/python-modules) to `makeInstancesUFO`, but we're not quite there yet

**Closed** 2016-03-04 08:05 UTC
Labels: question
