### ISSUE TITLE
Incorrect USE_MY_METRICS for some composite glyphs in 2.040

### ISSUE THREAD

**Issue by sevmeyer** [adobe-fonts/source-sans-pro#162] opened 2019-01-03 12:52 UTC
I noticed a possible regression in release 2.040 (TrueType flavor). In all composite glyphs, the first reference is marked with [USE_MY_METRICS][spec] (bit 0x0200). For some glyphs this seems incorrect and causes overlaps, at least on Linux:

![ssp2040-firefox](https://user-images.githubusercontent.com/12496525/50638548-1080ee80-0f56-11e9-975a-cac03f5037cf.png)
(OpenSuse Leap 15, Firefox)

![ssp2040-fontforge](https://user-images.githubusercontent.com/12496525/50638562-24c4eb80-0f56-11e9-9069-afbf7a29a7e6.png)
(FontForge)

Affected glyphs up to U+00FF:
U+0022 quotedbl
U+0025 percent
U+0060 grave
U+00A8 dieresis
U+00AB guillemotleft
U+00AF macron
U+00B4 acute
U+00B8 cedilla
U+00BB guillemotright
U+00BC onequarter
U+00BD onehalf
U+00BE threequarters
...

Release 2.020 does not have this issue.

[spec]: https://docs.microsoft.com/en-us/typography/opentype/spec/glyf

**Comment by frankrolf** [comment] 2019-01-03 17:57
Thank you for the detailed report. This seems to be the same as #161.
Unfortunately, I can reproduce some of what you’re seeing when saving a PDF with MS Word 2016 (16.0.9126.2336) using built-in “save” method.
Using Microsoft’s “print to PDF” creates a better document, but with some character substitutions.
However, I don’t see any issues at all when using “save as Adobe PDF”, which is a part of (paid) Acrobat DC.

Still investigating – originally this investigation was started to get to the bottom of #154 .

**Comment by miguelsousa** [comment] 2019-01-05 00:11
@sevmeyer thanks for bringing this issue to our attention. I did a `ttx` dump of the **percent** glyph and it confirmed your findings. The incorrect flag was set by the `ttfcomponentizer` tool. See https://github.com/adobe-type-tools/afdko/issues/709

**v2.020**
```
    <TTGlyph name="percent" xMin="35" yMin="-12" xMax="790" yMax="668">
      <component glyphName="zero.dnom" x="0" y="266" flags="0x4"/>
      <component glyphName="fraction" x="369" y="0" flags="0x4"/>
      <component glyphName="zero.dnom" x="457" y="0" flags="0x4"/>
    </TTGlyph>
```

**v2.040**
```
    <TTGlyph name="percent" xMin="35" yMin="-12" xMax="790" yMax="668">
      <component glyphName="zero.dnom" x="0" y="266" flags="0x204"/>
      <component glyphName="fraction" x="370" y="0" flags="0x4"/>
      <component glyphName="zero.dnom" x="457" y="0" flags="0x4"/>
    </TTGlyph>
```

**Comment by miguelsousa** [comment] 2019-01-09 05:40
The fix to the ttfcomponentizer is done. Need to fix a [second issue](https://github.com/adobe-type-tools/afdko/issues/710) before new TTF files can be made.

**Comment by miguelsousa** [comment] 2019-01-11 22:47
Fixed in this release https://github.com/adobe-fonts/source-sans-pro/releases/tag/2.045R-ro%2F1.095R-it

**Closed by miguelsousa** 2019-01-11 22:47 UTC
