### ISSUE TITLE
Unicode composing accent in cyrillic

### ISSUE THREAD

**Issue by Fuco1** [adobe-fonts/source-sans-pro#127] opened 2017-10-31 20:04 UTC
Hey!

I don't know if the problem is with the font or my application (Emacs), but I get some odd behaviour with combining unicode accents.

It seems to depend on the size and then either lowercase `a` or `e` changes to uppercase.  Observe:

![](https://i.imgur.com/8ca5N5F.png)

![](https://i.imgur.com/sXtQmZd.png)

Emacs is usually very good when it comes to unicode support, it can combine scripts such as devanagari or bengali which are very complex, so I'm not sure what the issue here is.  If anyone can give some hints it would be much appreciated :heart:

**Comment by frankrolf** [comment] 2017-10-31 20:42
That’s right, I can reproduce this problem in InDesign. 
1. compose sequence `е́ а́ é á x́  Е́ А́`
2. change to small caps

Pre-composed small caps work, small caps w/ anchor attachment don’t.
This issue won’t appear a lot in Latin context, because many Latin glyphs have a pre-composed accented version. However, not all Cyrillic glyphs do. 

That said, the mark feature is still somewhat experimental in Source Sans Pro, but it’s worth looking into fixing this. I suspect the mark feature writer needs to be run with some more flags enabled. 
FWIW, Source Serif has the same problem.

**Comment by pauldhunt** [comment] 2017-12-08 20:25
@Fuco1 can you please provide a full list of Cyrillic glyphs that can take accents?

**Comment by Fuco1** [comment] 2017-12-09 14:13
@pauldhunt I think these should be all

    а́ е́ и́ о́ у́ ы́ э́ ю́ я́

**Comment by Fuco1** [comment] 2017-12-09 14:14
Well, plus the upper case versions

    А́ Е́ И́ О́ У́ Ы́ Э́ Ю́ Я́

**Comment by erniemarch** [comment] 2018-09-13 21:34
checked in build 2.036 roman. these all look good.

**Comment by Fuco1** [comment] 2018-09-14 10:08
@erniemarch Where can I find the build?  The latest release on github I see is 2.020

**Comment by miguelsousa** [comment] 2018-09-14 17:19
@Fuco1 the new version is being tested now. We plan to release it soon.

**Comment by miguelsousa** [comment] 2018-10-30 19:57
Fixed in version 2.040.

**Closed by miguelsousa** 2018-10-30 19:57 UTC
Labels: addressed in source files, bug

**Comment by frankrolf** [comment] 2019-05-09 10:25
For posterity (after discussion with Krista Radoeva):
In Russian, the `ё` is also a vowel that may be stressed.
In Ukrainian, vowels `є` `і` and `ї` can take a stress mark.
In the context of textbooks for children, `ъ` `ь` may take a stress mark as well.

**Comment by frankrolf** [comment] 2019-05-09 10:52
@Fuco1 I can’t reproduce the regression you mentioned above. If you still can, please open a new issue.
